DELETE http://localhost:8080/events/5/register
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQxNjY5NDExLCJ1c2VySWQiOjJ9.lgcTDxJ-nf6Nz_xfPQVN7g9GahVoHqWcVbjV-oTdVTc
